# Generated by Django 2.1 on 2018-08-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superheros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('real_name', models.CharField(max_length=64)),
                ('comics', models.CharField(max_length=20)),
                ('powers', models.CharField(help_text='seperate with commas', max_length=255)),
            ],
        ),
    ]
